config/routes.rb
Rails.application.routes.draw do
  resources :sessions, only: [:new, :create] do
    collection do
      get :signout
    end
  end

  concern :commonable do
    collection do
      post :import
      get :download
      get :truncate
    end
  end

  resources :stocks, only: [:index, :new], concerns: :commonable
  resources :purchases, only: [:index, :new], concerns: :commonable

  resources :reports, only: [:index, :new], concerns: :commonable

  root 'reports#index'
end

app/models/stock.rb
class Stock < ApplicationRecord
  belongs_to :user
  extend StockCSVImporter

  class << self
    %w(name).each do |field|
      define_method field.pluralize do
        distinct.pluck(field.to_sym)
      end
    end
  end
end

app/controllers/stocks_controller.rb
class StocksController < ApplicationController
  before_action :search_stocks, only: [:index, :download]

  def index
    @stocks = @stocks.page(params[:page]).per(25)

    respond_to do |format|
      format.html
      format.js
    end
  end

  def import
    Stock.import(params[:file], current_user)
    redirect_to stocks_path
  end

  def truncate
    Stock.where(user_id: current_user.id).delete_all
    redirect_to new_stock_path
  end

  def download
    Spreadsheet.client_encoding = 'UTF-8'
    book = Spreadsheet::Workbook.new
    sheet1 = book.create_worksheet :name => 'Sheet1'
    format = Spreadsheet::Format.new color: :black, weight: :bold, size: 12
    sheet1.row(0).default_format = format

    sheet1.row(0).concat %w{品名 规格 包装单位 厂家 库存数量}
    @stocks.each_with_index do |stock, index|
      sheet1.row(index+1).push(*[stock.name, stock.size, stock.unit, stock.company, format("%.3f", stock.stock_volume)].flatten)
    end
    filepath = Rails.root + "public/exports/#{Date.today}.xls"
    book.write filepath
    send_file filepath
  end

  private
  def search_stocks
    @stocks = params[:search].blank? ? current_user.stocks.none : current_user.stocks.where(search_params)

    @stocks = @stocks.order(:name)
  end

  def search_params
    return download_params unless params[:stock].present?
    params[:stock].permit(name: []).to_unsafe_h.deep_delete_blank
  end

  def download_params
    { name: split_field(params[:name]) }.deep_delete_blank
  end

  def split_field(field)
    field.split(',') unless field.blank? || field.inquiry.null?
  end
end

app/views/stocks/_pagination.html.erb
  <div class="text-left record-count">
    &nbsp;&nbsp;第 <%= pagination_nums(@stocks) %> &nbsp;条记录 / 共 &nbsp;<%= @stocks.total_count %>&nbsp;条记录
  </div>
  <div class="text-right col-md">
    <%= paginate @stocks, remote: true %>
  </div>

app/views/stocks/_search_form.html.erb
<div><h4>库存商品查询</h4></div>
<div class="well well-lg">
  <%= form_for :stock, url: stocks_path, method: :get, html: {id: 'search-form', class: 'form-inline'}, remote: true do |f| %>
    <div class="row">
      <input type="hidden" class="form-control" name="search" value="<%= params[:search].presence || true %>" placeholder="品名">
      <div class="form-group col-md-4 col-lg-4">
        <label for="stock_name">品&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;名</label>
        <%= f.select :name, current_user.stocks.names, {}, {multiple: true, class: 'form-control'} %>
      </div>
    </div>
    <br>
    <div class="row">
      <div class="col-md-2 col-lg-2">
        <%= link_to '重置条件', '#', class: 'btn btn-default btn-block', id: 'clear' %>
      </div>
      <div class="col-md-2 col-lg-2">
      </div>
      <div class="col-md-2 col-lg-2 pull-left">
        <%= f.submit '搜索', class: 'btn btn-default btn-block', id: 'search' %>
      </div>
      <div class="col-md-2 col-lg-2">
      </div>
      <div class="col-md-2 col-lg-2">
        <%= link_to '下载', download_stocks_path, class: 'btn btn-default btn-block', id: 'download', target: '_blank' %>
      </div>
    </div>
  <% end %>
</div>

<script>
  $(document).ready(function() {
    $('select').multiselect({
      enableFiltering: true,
      nonSelectedText: '请选择',
      nSelectedText: '个选择',
      numberDisplayed: 1
    });

    $('#clear').click(function(){
      $('option', $('select')).each(function(element) {
        $(this).removeAttr('selected').prop('selected', false);
      });
      $('select').multiselect('refresh');
      $('.datepicker').val('');
      return false;
    });
  })
</script>

app/views/stocks/_stock.html.erb
<tr>
  <td><%= stock.name %></td>
  <td><%= stock.size %></td>
  <td><%= stock.unit %></td>
  <td><%= stock.company %></td>
  <td><%= format "%.3f", stock.stock_volume.to_f %></td>
</tr>

app/views/stocks/index.html.erb
<%= render 'search_form' %>

<div id="results" style="display: none">
  <table id="stock_table"  class="table table-bordered" cellspacing="0" width="100%">
    <thead>
      <tr>
        <th>品名</th>
        <th>规格</th>
        <th>包装单位</th>
        <th>厂家</th>
        <th>库存数量</th>
      </tr>
    </thead>
    <tbody id="content">
      <%= render partial: 'stock', collection: @stocks, as: :stock %>
    </tbody>
  </table>
  <div id="paginator">
    <%= render 'pagination' %>
  </div>
</div>

<script>
  $('#download').click(function(){
    var name = $('#stock_name').val();
    var downloadLink = $(this).attr('href');
    downloadLink += '?search=true&name=' + name;
    $(this).attr({'href': downloadLink});
    return true;
  });
</script>

app/views/stocks/index.js.erb
$("#results").show();
$("#content").html('');
$("#content").append("<%= j( render partial: 'stock', collection: @stocks, as: :stock ) %>");
$("#paginator").html("<%= j( render 'pagination' ) %>");

app/views/stocks/new.html.erb
<div class="container">
  <div class="bottom-line-auth"><h4>导入库存数据</h4></div>
  <hr>
  <%= form_tag import_stocks_path, multipart: true, class: 'form-line' do %>
    <div class="form-group">
      <%= label_tag '请选择xls文件' %>
      <%= file_field_tag :file, id: 'upload_input', class: 'form-control' %>
    </div>
    <div class="form-group">
      <%= submit_tag "导入", class: 'btn btn-info' %>
    </div>
  <% end %>

  <hr>
  <%= link_to '清空所有库存数据', truncate_stocks_path, class: 'btn btn-info', data: {confirm: '确定清空吗？'}%>
</div>