config/routes.rb
Rails.application.routes.draw do
  resources :sessions, only: [:new, :create] do
    collection do
      get :signout
    end
  end

  concern :commonable do
    collection do
      post :import
      get :download
      get :truncate
    end
  end

  resources :stocks, only: [:index, :new], concerns: :commonable
  resources :purchases, only: [:index, :new], concerns: :commonable

  resources :reports, only: [:index, :new], concerns: :commonable

  root 'reports#index'
end

app/controllers/purchases_controller.rb
class PurchasesController < ApplicationController
  before_action :search_purchases, only: [:index, :download]

  def index
    @purchases = @purchases.page(params[:page]).per(25)

    respond_to do |format|
      format.html
      format.js
    end
  end

  def new
  end

  def import
    Purchase.import(params[:file], current_user)
    redirect_to purchases_path
  end

  def truncate
    Purchase.where(user_id: current_user.id).delete_all
    redirect_to new_purchase_path
  end

  def download
    Spreadsheet.client_encoding = 'UTF-8'
    book = Spreadsheet::Workbook.new
    sheet1 = book.create_worksheet :name => 'Sheet1'
    format = Spreadsheet::Format.new color: :black, weight: :bold, size: 12
    sheet1.row(0).default_format = format

    sheet1.row(0).concat %w{上游客户 品名 规格 包装单位 厂家 日期 采购数量}
    @purchases.each_with_index do |purchase, index|
      sheet1.row(index+1).push(*[purchase.upstream_client, purchase.name, purchase.size, purchase.unit, purchase.company, purchase.purchase_date&.strftime('%F').to_s, format("%.3f", purchase.purchase_volume)].flatten)
    end
    filepath = Rails.root + "public/exports/#{Date.today}.xls"
    book.write filepath
    send_file filepath
  end

  private
  def search_purchases
    @purchases = params[:search].blank? ? current_user.purchases.none : current_user.purchases.where(search_params)

    conditions = []
    conditions << "purchase_date >= '#{params[:start_date].to_datetime.to_s(:db)}'" if params[:start_date].present?
    conditions << "purchase_date <= '#{params[:end_date].to_datetime.end_of_day.to_s(:db)}'" if params[:end_date].present?

    @purchases = @purchases.where(conditions.join(' AND ')) if conditions.present?
    @purchases = @purchases.order(:purchase_date)
  end

  def search_params
    return download_params unless params[:purchase].present?
    params[:purchase].permit(name: [], size: [], unit: [], company: [], upstream_client: []).to_unsafe_h.deep_delete_blank
  end

  def download_params
    %i(name size unit company upstream_client).inject({}) do |result, key|
      result[key] = split_field(params[key])
      result
    end.deep_delete_blank
  end

  def split_field(field)
    field.split(',') unless field.blank? || field.inquiry.null?
  end
end

app/views/purchases/_pagination.html.erb
  <div class="text-left record-count">
    &nbsp;&nbsp;第 <%= pagination_nums(@purchases) %> &nbsp;条记录 / 共 &nbsp;<%= @purchases.total_count %>&nbsp;条记录
  </div>
  <div class="text-right col-md">
    <%= paginate @purchases, remote: true %>
  </div>

app/views/purchases/_purchase.html.erb
<tr>
  <td><%= purchase.upstream_client %></td>
  <td><%= purchase.name %></td>
  <td><%= purchase.size %></td>
  <td><%= purchase.unit %></td>
  <td><%= purchase.company %></td>
  <td><%= purchase.purchase_date&.strftime('%F') %></td>
  <td><%= format "%.3f", purchase.purchase_volume.to_f %></td>
</tr>

app/views/purchases/_search_form.html.erb
<div><h4>采购明细查询</h4></div>
<div class="well well-lg">
  <%= form_for :purchase, url: purchases_path, method: :get, html: {id: 'search-form', class: 'form-inline'}, remote: true do |f| %>
    <div class="row">
      <input type="hidden" class="form-control" name="search" value="<%= params[:search].presence || true %>" placeholder="品名">
      <div class="form-group col-md-4 col-lg-4">
        <label for="purchase_name">品&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;名</label>
        <%= f.select :name, current_user.purchases.names, {}, {multiple: true, class: 'form-control'} %>
      </div>
      <div class="form-group col-md-4 col-lg-4">
        <label for="size" class="">规&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;格</label>
        <%= f.select :size, current_user.purchases.sizes, {}, {multiple: true, class: 'form-control'} %>
      </div>
      <div class="form-group col-md-4 col-lg-4">
        <label for="company" class="">生产厂家</label>
        <%= f.select :company, current_user.purchases.companies, {}, {multiple: true, class: 'form-control'} %>
      </div>
    </div>
    <div class="row">
      <div class="form-group col-md-4 col-lg-4">
        <label for="sell_date" class="">开始日期</label>
        <input type="text" class="form-control datepicker" name="start_date" value="<%= params[:start_date] %>" placeholder="开始日期">
      </div>
      <div class="form-group col-md-4 col-lg-4">
        <label for="sell_date" class="">截止日期</label>
        <input type="text" class="form-control datepicker" name="end_date" value="<%= params[:end_date] %>" placeholder="截止日期">
      </div>
      <div class="form-group col-md-4 col-lg-4">
        <label for="upstream_client" class="">上游客户</label>
        <%= f.select :upstream_client, current_user.purchases.upstream_clients, {}, {multiple: true, class: 'form-control'} %>
      </div>
    </div>
    <br>
    <div class="row">
      <div class="col-md-2 col-lg-2">
        <%= link_to '重置条件', '#', class: 'btn btn-default btn-block', id: 'clear' %>
      </div>
      <div class="col-md-2 col-lg-2">
      </div>
      <div class="col-md-2 col-lg-2 pull-left">
        <%= f.submit '搜索', class: 'btn btn-default btn-block', id: 'search' %>
      </div>
      <div class="col-md-2 col-lg-2">
      </div>
      <div class="col-md-2 col-lg-2">
        <%= link_to '下载', download_purchases_path, class: 'btn btn-default btn-block', id: 'download', target: '_blank' %>
      </div>
    </div>
  <% end %>
</div>

<script>
  $(document).ready(function() {
    $('select').multiselect({
      enableFiltering: true,
      nonSelectedText: '请选择',
      nSelectedText: '个选择',
      numberDisplayed: 1
    });

    $('#clear').click(function(){
      $('option', $('select')).each(function(element) {
        $(this).removeAttr('selected').prop('selected', false);
      });
      $('select').multiselect('refresh');
      $('.datepicker').val('');
      return false;
    });
  })
</script>

app/views/purchases/index.html.erb
<%= render 'search_form' %>

<div id="results" style="display: none">
  <table id="purchase_table"  class="table table-bordered" cellspacing="0" width="100%">
    <thead>
      <tr>
        <th style="max-width:250px;">上游客户</th>
        <th>品名</th>
        <th>规格</th>
        <th>包装单位</th>
        <th>厂家</th>
        <th>日期</th>
        <th>采购数量</th>
      </tr>
    </thead>
    <tbody id="content">
      <%= render partial: 'purchase', collection: @purchases, as: :purchase %>
    </tbody>
  </table>
  <div id="paginator">
    <%= render 'pagination' %>
  </div>
</div>

<script>
  $('#download').click(function(){
    var name = $('#purchase_name').val();
    var size = $('#purchase_size').val();
    var company = $('#purchase_company').val();
    var upstreamClient = $('#purchase_upstream_client').val();
    var startDate = $('input[name="start_date"]').val();
    var endDate = $('input[name="end_date"]').val();
    var downloadLink = $(this).attr('href');
    downloadLink += '?search=true&name=' + name + '&size='+ size + '&company=' + company;
    downloadLink += '&upstream_client=' + upstreamClient + '&start_date=' + startDate + '&end_date=' + endDate
    $(this).attr({'href': downloadLink});
    return validateForm();
  });

  $('#search').click(function(){
    return validateForm();
  });

  function validateForm(){
    var startDate = $('input[name="start_date"]').val();
    var endDate = $('input[name="end_date"]').val();
    if(startDate && endDate && (startDate > endDate)){
      alert('时间选择错误，请重新选择');
      return false;
    }
    return true;
  }

  $('.datepicker').pickadate({
    monthsFull: [ '一月', '二月', '三月', '四月', '五月', '六月', '七月', '八月', '九月', '十月', '十一月', '十二月' ],
    monthsShort: [ '一', '二', '三', '四', '五', '六', '七', '八', '九', '十', '十一', '十二' ],
    weekdaysFull: [ '星期日', '星期一', '星期二', '星期三', '星期四', '星期五', '星期六' ],
    weekdaysShort: [ '日', '一', '二', '三', '四', '五', '六' ],
    today: '今日',
    clear: '清除',
    close: '关闭',
    firstDay: 1,
    format: 'yyyy-mm-dd',
    formatSubmit: 'yyyy/mm/dd'
  });
</script>

app/views/purchases/index.js.erb
$("#results").show();
$("#content").html('');
$("#content").append("<%= j( render partial: 'purchase', collection: @purchases, as: :purchase ) %>");
$("#paginator").html("<%= j( render 'pagination' ) %>");

app/views/purchases/new.html.erb
<div class="container">
  <div class="bottom-line-auth"><h4>导入采购数据</h4></div>
  <hr>
  <%= form_tag import_purchases_path, multipart: true, class: 'form-line' do %>
    <div class="form-group">
      <%= label_tag '请选择xls文件' %>
      <%= file_field_tag :file, id: 'upload_input', class: 'form-control' %>
    </div>
    <div class="form-group">
      <%= submit_tag "导入", class: 'btn btn-info' %>
    </div>
  <% end %>

  <hr>
  <%= link_to '清空所有采购数据', truncate_purchases_path, class: 'btn btn-info', data: {confirm: '确定清空吗？'}%>
</div>