config/routes.rb
Rails.application.routes.draw do
  resources :sessions, only: [:new, :create] do
    collection do
      get :signout
    end
  end

  concern :commonable do
    collection do
      post :import
      get :download
      get :truncate
    end
  end

  resources :stocks, only: [:index, :new], concerns: :commonable
  resources :purchases, only: [:index, :new], concerns: :commonable

  resources :reports, only: [:index, :new], concerns: :commonable

  root 'reports#index'
end

app/models/report.rb
class Report < ApplicationRecord
  belongs_to :user
  extend CSVImporter

  class << self
    %w(name size company target_company unit).each do |field|
      define_method field.pluralize do
        distinct.pluck(field.to_sym)
      end
    end
  end
end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController
  before_action :search_reports, only: [:index, :download]

  def index
    @reports = @reports.page(params[:page]).per(25)

    respond_to do |format|
      format.html
      format.js
    end
  end

  def import
    Report.import(params[:file], current_user)
    redirect_to reports_path
  end

  def truncate
    Report.where(user_id: current_user.id).delete_all
    redirect_to new_report_path
  end

  def download
    Spreadsheet.client_encoding = 'UTF-8'
    book = Spreadsheet::Workbook.new
    sheet1 = book.create_worksheet :name => 'Sheet1'
    format = Spreadsheet::Format.new color: :black, weight: :bold, size: 12
    sheet1.row(0).default_format = format

    sheet1.row(0).concat %w{品名 规格 包装单位 厂家 日期 往来单位名称 出库数量}
    @reports.each_with_index do |report, index|
      sheet1.row(index+1).push(*[report.name, report.size, report.unit, report.company, report.sell_date&.strftime('%F').to_s, report.target_company, format("%.3f", report.sell_volume)].flatten)
    end
    filepath = Rails.root + "public/exports/#{Date.today}.xls"
    book.write filepath
    send_file filepath
  end

  private
  def search_reports
    @reports = params[:search].blank? ? current_user.reports.none : current_user.reports.where(search_params)

    conditions = []
    conditions << "sell_date >= '#{params[:start_date].to_datetime.to_s(:db)}'" if params[:start_date].present?
    conditions << "sell_date <= '#{params[:end_date].to_datetime.end_of_day.to_s(:db)}'" if params[:end_date].present?

    @reports = @reports.where(conditions.join(' AND ')) if conditions.present?
    @reports = @reports.order(:sell_date)
  end

  def search_params
    return download_params unless params[:report].present?
    params[:report].permit(name: [], size: [], unit: [], company: [], target_company: []).to_unsafe_h.deep_delete_blank
  end

  def download_params
    %i(name size unit company target_company).inject({}) do |result, key|
      result[key] = split_field(params[key])
      result
    end.deep_delete_blank
  end

  def split_field(field)
    field.split(',') unless field.blank? || field.inquiry.null?
  end
end

app/views/reports/_pagination.html.erb
  <div class="text-left record-count">
    &nbsp;&nbsp;第 <%= pagination_nums(@reports) %> &nbsp;条记录 / 共 &nbsp;<%= @reports.total_count %>&nbsp;条记录
  </div>
  <div class="text-right col-md">
    <%= paginate @reports, remote: true %>
  </div>

app/views/reports/_report.html.erb
<tr>
  <td><%= report.name %></td>
  <td><%= report.size %></td>
  <td><%= report.unit %></td>
  <td><%= report.company %></td>
  <td><%= report.sell_date&.strftime('%F') %></td>
  <td><%= report.target_company %></td>
  <td><%= format "%.3f", report.sell_volume.to_f %></td>
</tr>

app/views/reports/_search_form.html.erb
<div><h4>商品流向查询</h4></div>
<div class="well well-lg">
  <%= form_for :report, url: reports_path, method: :get, html: {id: 'search-form', class: 'form-inline'}, remote: true do |f| %>
    <div class="row">
      <div class="form-group col-md-4 col-lg-4">
        <label for="sell_date" class="">开始日期</label>
        <input type="text" class="form-control datepicker" name="start_date" value="<%= params[:start_date] %>" placeholder="开始日期">
      </div>
      <div class="form-group col-md-4 col-lg-4">
        <label for="sell_date" class="">截止日期</label>
        <input type="text" class="form-control datepicker" name="end_date" value="<%= params[:end_date] %>" placeholder="截止日期">
      </div>
      <div class="form-group col-md-4 col-lg-4">
        <label for="target_company" class="">往来单位</label>
        <%= f.select :target_company, current_user.reports.target_companies, {}, {multiple: true, class: 'form-control'} %>
      </div>
    </div>
    <div class="row">
      <input type="hidden" class="form-control" name="search" value="<%= params[:search].presence || true %>" placeholder="品名">
      <div class="form-group col-md-4 col-lg-4">
        <label for="report_name">品&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;名</label>
        <%= f.select :name, current_user.reports.names, {}, {multiple: true, class: 'form-control'} %>
      </div>
      <div class="form-group col-md-4 col-lg-4">
        <label for="size" class="">规&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;格</label>
        <%= f.select :size, current_user.reports.sizes, {}, {multiple: true, class: 'form-control'} %>
      </div>
      <div class="form-group col-md-4 col-lg-4">
        <label for="company" class="">厂&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;家</label>
        <%= f.select :company, current_user.reports.companies, {}, {multiple: true, class: 'form-control'} %>
      </div>
    </div>
    <div class="row">
      <div class="form-group col-md-4 col-lg-4">
        <label for="report_name">包装单位</label>
        <%= f.select :unit, current_user.reports.units, {}, {multiple: true, class: 'form-control'} %>
      </div>
      <div class="form-group col-md-4 col-lg-4">
        <label for="size" class="">商品编号</label>
        <input type="text" class="form-control disabled" name="num" disabled placeholder="商品编号">
      </div>
      <div class="form-group col-md-4 col-lg-4">
        <label for="size" class="">单位编号</label>
        <input type="text" class="form-control disabled" name="num" disabled placeholder="单位编号">
      </div>
      <div class="form-group col-md-4 col-lg-4">
        <label for="size" class="">单位名称</label>
        <input type="text" class="form-control disabled" name="num" disabled placeholder="单位名称">
      </div>
      <div class="form-group col-md-4 col-lg-4">
        <label for="size" class="">供应商编号</label>
        <input type="text" class="form-control disabled" name="num" disabled placeholder="供应商编号">
      </div>
      <div class="form-group col-md-4 col-lg-4">
        <label for="size" class="">供应商名称</label>
        <input type="text" class="form-control disabled" name="num" disabled placeholder="供应商名称">
      </div>
      <div class="form-group col-md-4 col-lg-4">
        <label for="size" class="">流向卡号</label>
        <input type="text" class="form-control disabled" name="num" disabled placeholder="流向卡号">
      </div>
      <div class="form-group col-md-4 col-lg-4">
        <label for="size" class="">流向卡名称</label>
        <input type="text" class="form-control disabled" name="num" disabled placeholder="流向卡名称">
      </div>
    </div>

    <br>
    <div class="row">
      <div class="col-md-2 col-lg-2">
        <%= link_to '重置条件', '#', class: 'btn btn-default btn-block', id: 'clear' %>
      </div>
      <div class="col-md-2 col-lg-2">
      </div>
      <div class="col-md-2 col-lg-2 pull-left">
        <%= f.submit '搜索', class: 'btn btn-default btn-block', id: 'search' %>
      </div>
      <div class="col-md-2 col-lg-2">
      </div>
      <div class="col-md-2 col-lg-2">
        <%= link_to '下载', download_reports_path, class: 'btn btn-default btn-block', id: 'download', target: '_blank' %>
      </div>
    </div>
  <% end %>
</div>

<script>
  $(document).ready(function() {
    $('select').multiselect({
      enableFiltering: true,
      nonSelectedText: '请选择',
      nSelectedText: '个选择',
      numberDisplayed: 1
    });

    $('#clear').click(function(){
      $('option', $('select')).each(function(element) {
        $(this).removeAttr('selected').prop('selected', false);
      });
      $('select').multiselect('refresh');
      $('.datepicker').val('');
      return false;
    });
  })
</script>

app/views/reports/index.html.erb
<%= render 'search_form' %>

<div id="results" style="display: none">
  <table id="report_table"  class="table table-bordered" cellspacing="0" width="100%">
    <thead>
      <tr>
        <th>品名</th>
        <th>规格</th>
        <th>包装单位</th>
        <th>厂家</th>
        <th>日期</th>
        <th style="width:250px;">往来单位名称</th>
        <th>出库数量</th>
      </tr>
    </thead>
    <tbody id="content">
      <%= render partial: 'report', collection: @reports, as: :report%>
    </tbody>
  </table>
  <div id="paginator">
    <%= render 'pagination' %>
  </div>
</div>

<script>
  $('#download').click(function(){
    var name = $('#report_name').val();
    var size = $('#report_size').val();
    var company = $('#report_company').val();
    var targetCompany = $('#report_target_company').val();
    var startDate = $('input[name="start_date"]').val();
    var endDate = $('input[name="end_date"]').val();
    var downloadLink = $(this).attr('href');
    downloadLink += '?search=true&name=' + name + '&size='+ size + '&company=' + company;
    downloadLink += '&target_company=' + targetCompany + '&start_date=' + startDate + '&end_date=' + endDate
    $(this).attr({'href': downloadLink});
    return validateForm();
  });

  $('#search').click(function(){
    return validateForm();
  });

  function validateForm(){
    var startDate = $('input[name="start_date"]').val();
    var endDate = $('input[name="end_date"]').val();
    if(startDate && endDate && (startDate > endDate)){
      alert('时间选择错误，请重新选择');
      return false;
    }
    return true;
  }

  $('.datepicker').pickadate({
    monthsFull: [ '一月', '二月', '三月', '四月', '五月', '六月', '七月', '八月', '九月', '十月', '十一月', '十二月' ],
    monthsShort: [ '一', '二', '三', '四', '五', '六', '七', '八', '九', '十', '十一', '十二' ],
    weekdaysFull: [ '星期日', '星期一', '星期二', '星期三', '星期四', '星期五', '星期六' ],
    weekdaysShort: [ '日', '一', '二', '三', '四', '五', '六' ],
    today: '今日',
    clear: '清除',
    close: '关闭',
    firstDay: 1,
    format: 'yyyy-mm-dd',
    formatSubmit: 'yyyy/mm/dd'
  });
</script>

app/views/reports/index.js.erb
$("#results").show();
$("#content").html('');
$("#content").append("<%= j( render partial: 'report', collection: @reports, as: :report ) %>");
$("#paginator").html("<%= j( render 'pagination' ) %>");

app/views/reports/new.html.erb
<div class="container">
  <div class="bottom-line-auth"><h4>导入销售数据</h4></div>
  <hr>
  <%= form_tag import_reports_path, multipart: true, class: 'form-line' do %>
    <div class="form-group">
      <%= label_tag '请选择xls文件' %>
      <%= file_field_tag :file, id: 'upload_input', class: 'form-control' %>
    </div>
    <div class="form-group">
      <%= submit_tag "导入", class: 'btn btn-info' %>
    </div>
  <% end %>

  <hr>
  <%= link_to '清空所有销售数据', truncate_reports_path, class: 'btn btn-info', data: {confirm: '确定清空吗？'}%>
</div>